baseURL = "http://lambda-class.com/"
languageCode = "en-us"
title = "Lambda-class"
theme = "blackburn"

#baseurl = "http://www.lambda-class.com/" # Make sure to end baseurl with a '/'
#title = "Your site title"
author = "Your name"
# Shown in the side menu
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 5

[indexes]
  tag = "tags"
  topic = "topics"
  categorie = "categories"

[params]
  # Shown in the home page
  subtitle = "Information Bus"
  brand = "Lambda-Class"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "Jan 02 2006"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 5
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "alexsanbhz"
  #gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  #facebook = "*"
  #googleplus = "*"
  #weibo = "*"
  #tumblr = "*"

  # SNS photo/video sharing
  instagram = "alexsanbhz/"
  #flickr = "*"
  #photo500px = "*"
  #pinterest = "*"
  #youtube = "*"
  #vimeo = "*"
  #vine = "*"
  #slideshare = "*"

  # SNS career oriented
  linkedin = "assilva/"
  #xing = "*"

  # SNS news
  #reddit = "*"
  #hackernews = "*"

  # Techie
  github = "alex-santiago/"
  #gitlab = "*"
  #bitbucket = "*"
  #stackoverflow = "*"
  #serverfault = "*"

  # Gaming
  #steam = "*"
  #mobygames = "*"

  # Music
  #lastfm = "*"
  #discogs = "*"

  # Other
  #keybase = "*"